name: TropicAPI
version: '1.4.0-Development'
main: com.okbeanok.tropicapi.TropicAPI
api-version: '1.21'
author: OkBeanOk
description: TropicAPI is a core library for other Tropic plugins.
website: https://github.com/okbeanok/tropicchatcore