name: TropicAPI
version: '1.4.2-Development'
main: com.okbeanok.tropicapi.TropicAPI
api-version: '1.21'
author: OkBeanOk, MigrateAccount
description: TropicAPI is a core library for other Tropica plugins.
website: https://github.com/OkBeanOk/TropicAPI